### ISSUE TITLE
"now domains add" throws an error

### ISSUE THREAD

**Issue by ide** [zeit/now-issues#18]
When adding a domain I get:

```
> Verifying nameservers…
> Verification OK!
> Error! Unknown error: TypeError: Cannot read property 'uid' of undefined
    at /Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/build/bin/now-domains:2:3331
    at tryCatch (/Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/regenerator-runtime/runtime.js:95:21)
    at tryCatch (/Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/regenerator-runtime/runtime.js:278:24)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
    at run (/Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)
```

`now alias` has a similar problem:

```
> Verification OK!
> Error! Unknown error: TypeError: Cannot read property 'created' of undefined
    at r.<anonymous> (/Users/ide/.nvm/versions/node/v6.3.1/lib/node_modules/now/build/lib/alias.js:1:6930)
```

```
$ now --version
𝚫 now 0.20.0
```

**Comment by OlliV** [comment]
There were two separate issues:
a) A premium account is required for `now domain` and `now alias`.
b) `babel-runtime` version used by `now` command didn't handle exceptions properly and thus the cli failed to print a proper error message, we are going to release a new version of `now` soon to fix that.
