### ISSUE TITLE
EACCES: permission denied, open './log.txt'

### ISSUE THREAD

**Issue by MiguhRuiz** [zeit/now-issues#23]
Hi there 😄 !

I'm trying to deploy [this app](https://github.com/MiguhRuiz/image-gallery) but when `npm start`starts there is an error because a depency needs to open a file called `log.txt`but it isn't allowed. What can I do in order to give the application this permissions when I want to deploy it? I mean, there is a flag on the now CLI to allow sudo or something like that? Any ideas?

## Console log

```
miguhruiz@MacBook-de-Miguh: ~/Dropbox/dev/image-gall[56bef3d] ⍉ 17:18
> now
> Deploying ~/Dropbox/dev/image-gallery
> Using Node.js 6.2.1 (default)
> Ready! https://image-gallery-lzmgdfqdew.now.sh (copied to clipboard) [1s]
> Initializing…
> Building
> Installing package fstream@~1.0.10
> Installing package fstream-ignore@~1.0.5
> Installing package once@~1.3.3
> Installing package readable-stream@~2.1.4
> Installing package rimraf@~2.5.1
> Installing package tar@~2.2.1
> Installing package uid-number@~0.0.6
> Installing package fstream@^1.0.0
> Installing package inherits@2
> Installing package minimatch@^3.0.0
> prebuild info begin Prebuild version 4.2.2
> gyp http GET https://nodejs.org/download/release/v6.2.1/node-v6.2.1-headers.tar.gz
> gyp http 200 https://nodejs.org/download/release/v6.2.1/node-v6.2.1-headers.tar.gz
> gyp http GET https://nodejs.org/download/release/v6.2.1/SHASUMS256.txt
> gyp http 200 https://nodejs.org/download/release/v6.2.1/SHASUMS256.txt
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/src/node_modules/66ff66b8adabc862d31d0d8dfcd5b3b842a0699c/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/.node-gyp/6.2.1/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/nowuser/.node-gyp/6.2.1',
> gyp info spawn args   '-Dnode_gyp_dir=/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84',
> gyp info spawn args   '-Dnode_lib_file=node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/nowuser/src/node_modules/66ff66b8adabc862d31d0d8dfcd5b3b842a0699c',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/home/nowuser/src/node_modules/66ff66b8adabc862d31d0d8dfcd5b3b842a0699c/build'
>   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o
> warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
> 1 warning generated.
>   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_impl.o
> warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
> In file included from ../deps/leveldb/leveldb-1.18.0/db/db_impl.cc:7:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/algorithm:62:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/bits/stl_algo.h:66:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/random:50:
> /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/x86_64-alpine-linux-musl/bits/opt_random.h:33:10: fatal error: 'x86intrin.h' file not found
> #include <x86intrin.h>
>          ^
> 1 warning and 1 error generated.
> make: Leaving directory '/home/nowuser/src/node_modules/66ff66b8adabc862d31d0d8dfcd5b3b842a0699c/build'
> deps/leveldb/leveldb.target.mk:145: recipe for target 'Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_impl.o' failed
> make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_impl.o] Error 1
> prebuild ERR! build error
> prebuild ERR! stack Error: `make` failed with exit code: 2
> prebuild ERR! stack     at ChildProcess.onExit (/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/lib/build.js:276:23)
> prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
> prebuild ERR! stack     at emitTwo (events.js:106:13)
> prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
> prebuild ERR! not ok
> prebuild ERR! build Error: `make` failed with exit code: 2
> prebuild ERR! build     at ChildProcess.onExit (/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/lib/build.js:276:23)
> prebuild ERR! build     at emitTwo (events.js:106:13)
> prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
> prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
> Error: Command prebuild --install ended with code 2
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:852:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.6.28
> node-pre-gyp info using node@6.2.1 | linux | x64
> node-pre-gyp info check checked for "/home/nowuser/src/node_modules/e7274f706150ca030b52ff64706dd84475808864/lib/binding/node-v48-linux-x64/node_sqlite3.node" (not found)
> node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v48-linux-x64.tar.gz
> node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v48-linux-x64.tar.gz
> node-pre-gyp info install unpacking node_sqlite3.node
> node-pre-gyp info tarball done parsing tarball
> node-pre-gyp info validate Running test command: '/usr/bin/node --eval 'require(\'/home/nowuser/src/node_modules/e7274f706150ca030b52ff64706dd84475808864/lib/binding/node-v48-linux-x64/node_sqlite3.node\')''
> [sqlite3] Success: "/home/nowuser/src/node_modules/e7274f706150ca030b52ff64706dd84475808864/lib/binding/node-v48-linux-x64/node_sqlite3.node" is installed via remote
> node-pre-gyp info ok
> ▲ npm run build
> [15:11:50] Using gulpfile ~/src/gulpfile.js
> [15:11:50] Starting 'build'...
> [15:11:50] Finished 'build' after 25 ms
> build exited with status 0
> ▲ npm start
> [APP] Server listening on 3000
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> Error: EACCES: permission denied, open './log.txt'
>     at Error (native)
> Error Error: Command node index.js ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:852:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by leo** [comment]
https://github.com/zeit/now/issues/18
