### ISSUE TITLE
handle.writeLatin1String is not a function on Node 6.5

### ISSUE THREAD

**Issue by quarterto** [zeit/now-issues#31]
Works fine on earlier versions of 6.x.

```js
net.js:732
      return handle.writeLatin1String(req, data);
                    ^

TypeError: handle.writeLatin1String is not a function
    at createWriteReq (net.js:732:21)
    at Socket._writeGeneric (net.js:702:11)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at clearBuffer (_stream_writable.js:414:7)
    at Socket.Writable.uncork (_stream_writable.js:243:7)
    at ClientRequest._flushOutput (_http_outgoing.js:666:10)
    at ClientRequest.OutgoingMessage._flush (_http_outgoing.js:640:16)
    at _http_client.js:195:10
    at callSocketMethod (_http_client.js:591:7)
```

**Comment by leo** [comment]
https://github.com/zeit/now/issues/23
