### ISSUE TITLE
`now-alias` doesn't work if there's an underscore in the domain name

### ISSUE THREAD

**Issue by leo** [zeit/now-issues#5]
@domderen reported this error:

```
now alias https://chained-lightning-ui-fbontxfmdb.now.sh deploy_per_branch.chainsaw.staging-owl.com.
> deploy_per_branch.chainsaw.staging-owl.com is a custom domain.
> Verifying the DNS settings for deploy_per_branch.chainsaw.staging-owl.com (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for deploy_per_branch.chainsaw.staging-owl.com
> Error! Unknown error: Error
    at r.<anonymous> (/Users/dominik/.nvm/versions/node/v6.3.1/lib/node_modules/now/build/lib/alias.js:1:13699)
    at tryCatch (/Users/dominik/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/dominik/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/dominik/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:121:21)
    at step (/Users/dominik/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/dominik/.nvm/versions/node/v6.3.1/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by leo** [comment]
Duplicate of https://github.com/zeit/now-issues/issues/4
