### ISSUE TITLE
npm install issues with node-gyp and node 6.2.1

### ISSUE THREAD

**Issue by bpartridge83** [zeit/now-issues#9]
Could be related to https://github.com/nodejs/node-gyp/issues/809, but it doesn't look like there's much of a resolution yet there.

```
> Initializing…
> Building
> ▲ npm install
> Installing package fstream@~1.0.10
> Installing package fstream-ignore@~1.0.5
> Installing package once@~1.3.3
> Installing package readable-stream@~2.1.4
> Installing package rimraf@~2.5.1
> Installing package tar@~2.2.1
> Installing package uid-number@~0.0.6
> Installing package fstream@^1.0.0
> Installing package inherits@2
> Installing package minimatch@^3.0.0
> Warning: using slow naiv Buffer.indexOf function!
> `npm install buffertools` to speed things up.
> try to read file /usr/share/unicode/UnicodeData.txt …
> try to read file /usr/share/unicode-data/UnicodeData.txt …
> /usr/share/unicode/UnicodeData.txt not found.
> /usr/share/unicode-data/UnicodeData.txt not found.
> try to read file UnicodeData.txt …
> UnicodeData.txt not found.
> saving data as Lm.js …
> saving data as Mn.js …
> saving data as Me.js …
> saving data as Mc.js …
> saving data as Nl.js …
> saving data as Zl.js …
> saving data as Zp.js …
> saving data as Cs.js …
> saving data as Co.js …
> done.
> gyp
>  
> info 
> it worked if it ends with
>  ok
> gyp
>  
> gyp info 
> info using node-gyp@3.3.1
> using node@6.2.1 | linux | x64
>  
> gyp
>  
> GET https://nodejs.org/download/release/v6.2.1/node-v6.2.1-headers.tar.gz
> http
> gyp
>  http 200 https://nodejs.org/download/release/v6.2.1/node-v6.2.1-headers.tar.gz
> gyp
>  http GET
>  https://nodejs.org/download/release/v6.2.1/SHASUMS256.txt
>  http 200
> gyp
>  https://nodejs.org/download/release/v6.2.1/SHASUMS256.txt
> gyp
>  info 
> spawn
>  info spawn args
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info
> info 
> spawn args   'binding.gyp',
> gyp
>  /usr/bin/python2
>    '-f',
>  spawn args
> gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
> gyp 
>    '/home/nowuser/src/node_modules/ca4c8fce4e803f9a8aa5a515ecd109e82822d37e/build/config.gypi',
> gyp info spawn args   '-I',
> gyp
>  info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
> gyp 
>  info
> info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/.node-gyp/6.2.1/include/node/common.gypi',
> gyp info spawn args
> spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/nowuser/.node-gyp/6.2.1',
> gyp info
>  
>    '-Dlibrary=shared_library',
> gyp
>  
>  spawn args   '-Goutput_dir=.' ]
> spawn args
>    '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=node.lib',
> gyp info spawn args
>  spawn args   '--generator-output',
> gyp
>    '-Dmodule_root_dir=/home/nowuser/src/node_modules/ca4c8fce4e803f9a8aa5a515ecd109e82822d37e',
> gyp info spawn args   '--depth=.',
> gyp info spawn args
>    '--no-parallel',
> gyp 
> info
>  info 
> gyp info
> spawn args   'build',
> gyp info
>  spawn
>  make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/home/nowuser/src/node_modules/ca4c8fce4e803f9a8aa5a515ecd109e82822d37e/build'
>   CXX(target) Release/obj.target/buffertools/buffertools.o
> /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/x86_64-alpine-linux-musl/bits/opt_random.h:33:10: fatal error: 'x86intrin.h' file not found
> #include <x86intrin.h>
>          ^
> In file included from ../buffertools.cc:22:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/algorithm:62:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/bits/stl_algo.h:66:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/random:50:
> 1 error generated.
> buffertools.target.mk:86: recipe for target 'Release/obj.target/buffertools/buffertools.o' failed
> make: Leaving directory '/home/nowuser/src/node_modules/ca4c8fce4e803f9a8aa5a515ecd109e82822d37e/build'
> make: *** [Release/obj.target/buffertools/buffertools.o] Error 1
> gyp ERR! build error 
> gyp
>  
> ERR!
> stack
>  
>      at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
>  Error: `make` failed with exit code: 2
> ERR!
>  
>  
> stack
> gyp
>  
> stack
> ERR!
>  
> gyp
>      at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp 
> gyp
> ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
> ERR!
>  System
> gyp
>  Linux 4.6.0-coreos
>  ERR!
>  
>  
>  command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
> gyp
> cwd
> ERR!
>  /home/nowuser/src/node_modules/ca4c8fce4e803f9a8aa5a515ecd109e82822d37e
> gyp
>  
> not ok 
>  
> ERR!
>  node -v v6.2.1
> gyp
>  ERR!
>  
> node-gyp -v
>  v3.3.1
> gyp
>  
> ERR!
>  
> Error: Command node-gyp rebuild ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:852:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> node-pre-gyp
>  
> info it worked if it ends with ok
>  info using
>  info using node@6.2.1 | linux | x64
>  node-pre-gyp@0.6.29
> node-pre-gyp
> node-pre-gyp
>  info 
> check
>  checked for "/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/lib/binding/Release/node-v48-linux-x64/fse.node" (not found)
> http
> node-pre-gyp 
>  https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
>  
> GET
> node-pre-gyp
> node-pre-gyp
>  http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
> node-pre-gyp ERR! 
> Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@6.2.1 (node-v48 ABI) (falling back to source compile with node-gyp) 
> node-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz 
> gyp
> info
>  
>  
> it worked if it ends with
>  ok
>  
> info
> gyp
>  
> using node-gyp@3.4.0
> gyp info using node@6.2.1 | linux | x64
> gyp
>  info ok 
> gyp
>  
> info it worked if it ends with ok
>  
> gyp
>  
> info
> gyp
> using
> using node@6.2.1 | linux | x64
>  node-gyp@3.4.0
>  
> info
>  
> gyp
>  info spawn
>  /usr/bin/python2
> gyp
> gyp 
> info
>    'binding.gyp',
> info
>  
>  [ '/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/gyp/gyp_main.py',
> gyp
>  info spawn args
> spawn args
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info 
>  info 
>  spawn args   '-I',
> gyp 
>    '-f',
> gyp info spawn args   'make',
> spawn args   '/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/addon.gypi',
> gyp 
> spawn args
>  info
>  
> spawn args
>    '-Dvisibility=default',
> gyp
> spawn args
>  
>    '-Dnode_root_dir=/home/nowuser/.node-gyp/6.2.1',
> gyp info
>  spawn args
> info
>    '-Dnode_gyp_dir=/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84',
> info spawn args   '/home/nowuser/.node-gyp/6.2.1/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp 
> gyp info spawn args   '-Dnode_lib_file=node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f',
> gyp info spawn args   '--depth=.',
> gyp info spawn args
>    '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info
>  ok 
> gyp
>  
> info it worked if it ends with ok
> info
>  node-gyp@3.4.0
> gyp
> gyp info 
>  using
>  
> using node@6.2.1 | linux | x64
> gyp
>  info spawn
>  make
> gyp info spawn args
>  [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/build'
>   SOLINK_MODULE(target) Release/obj.target/.node
>   COPY Release/.node
> make: Leaving directory '/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/build'
>  
> gyp
>  
> info
>  
> ok
>  info ok 
> node-pre-gyp
> Binary downloaded and installed at /home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/vendor/linux-x64-48/binding.node
> "/home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/vendor/linux-x64-48/binding.node" exists. 
>  testing binary.
> Problem with the binary:
> Error: Error relocating /home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/vendor/linux-x64-48/binding.node: __strtod_internal: symbol not found
> Manual build incoming.
> Building: /usr/bin/node /home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> gyp
>  
> info it worked if it ends with ok
> gyp
>  
> verb
>  cli [ '/usr/bin/node',
> gyp verb cli   '/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/bin/node-gyp.js',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb 
> cli   '--libsass_ldflags=',
> gyp verb
> verb
> cli
>  
>  
> verb
>  cli   '--libsass_cflags=',
> gyp 
>    '--libsass_ext=',
>  rebuild []
>  
>  
> cli   '--libsass_library=' ]
>  
> gyp
> info
>  node-gyp@3.4.0
> using
> gyp
> gyp info 
> using
>  node@6.2.1 | linux | x64
> verb
> gyp
>  
> command
>  
>  verb
>  command
> gyp
>  clean []
> gyp
>  
>  verb
> clean
>  removing "build" directory
>  verb 
> gyp
> command
>  configure []
> gyp
>  verb check python checking for Python executable "python2" in the PATH
> verb
> gyp
>  
>  
> `which` succeeded
>  python2 /usr/bin/python2
> gyp
>  verb check python version
>  `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
>  verb get node dir
> gyp
>  no --target version specified, falling back to host node version: 6.2.1
> gyp verb
>  command install [ '6.2.1' ]
> gyp
>  
>  verb install input version string "6.2.1"
> verb 
> install
> gyp
>  installing version: 6.2.1
> gyp 
> verb install
>  --ensure was passed, so won't reinstall if already installed
>  verb 
> gyp
> install
>  version is already installed, need to check "installVersion"
>  9
> needs "installVersion"
> gyp
>  
> verb
>  
>  version is good
>  9
> gyp
>  verb
>  
> install
>  get node dir target node version installed: 6.2.1
> gyp
>  verb
>  
>  verb
> got "installVersion"
> gyp
>  verb 
> gyp
> verb build dir "build" dir needed to be created? /home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/build
> build dir attempting to create "build" dir: /home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/build
> gyp 
>  verb
> gyp
>  
> build/config.gypi creating config file
>  verb 
> gyp
> build/config.gypi
>  writing out config file: /home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/build/config.gypi
>  verb
> gyp
>  
> gyp
>  checking for gypi file: /home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/config.gypi
> config.gypi
>  verb common.gypi checking for gypi file: /home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/common.gypi
>  
> verb gyp
> gyp
>  gyp format was not specified; forcing "make"
>  info
> gyp
>  /usr/bin/python2
> spawn
>  
> gyp
> info
> gyp
>  
>    'make',
>  
> spawn args
>    'binding.gyp',
> gyp info 
> spawn args
>    '-f',
> gyp info 
> spawn args
>  
> gyp
>  
> info 
> spawn args
>    '-I',
> gyp
>  
> spawn args
> info
>  
>    '/home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/build/config.gypi',
> gyp
> info
>  
> spawn args
>    '-I',
> gyp
>  
> info
>  
> spawn args
>    '/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/addon.gypi',
> gyp
>    '-I',
>  
> info
>  
> spawn args
>    '/home/nowuser/.node-gyp/6.2.1/include/node/common.gypi',
> gyp
>  
>  
> spawn args
> info
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/nowuser/.node-gyp/6.2.1',
> gyp info spawn args   '-Dnode_gyp_dir=/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84',
> gyp info spawn args   '-Dnode_lib_file=node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
>  info spawn args [ '/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/gyp/gyp_main.py',
>  verb
>  
> command
> gyp
>  build []
> gyp
> verb
>  
>  
> build type
> gyp
>  Release
>  
>  
> architecture
> verb
>  x64
> gyp
>  
>  
> verb
> node dev dir
>  /home/nowuser/.node-gyp/6.2.1
>  /usr/bin/make
> gyp
>  
>  
> `which` succeeded for `make`
> verb
> gyp
>  
> info
>  
> spawn
>  make
> gyp info 
> spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/build'
>   clang++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.6"' -I/home/nowuser/.node-gyp/6.2.1/include/node -I/home/nowuser/.node-gyp/6.2.1/src -I/home/nowuser/.node-gyp/6.2.1/deps/uv/include -I/home/nowuser/.node-gyp/6.2.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
> In file included from ../src/libsass/src/ast.cpp:2:
> In file included from ../src/libsass/src/ast.hpp:11:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/algorithm:62:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/bits/stl_algo.h:66:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/random:50:
> /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/x86_64-alpine-linux-musl/bits/opt_random.h:33:10: fatal error: 'x86intrin.h' file not found
> #include <x86intrin.h>
>          ^
> 1 error generated.
> src/libsass.target.mk:138: recipe for target 'Release/obj.target/libsass/src/libsass/src/ast.o' failed
> make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
> make: Leaving directory '/home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6/build'
>  
> gyp
> ERR!
>  
> build error 
> gyp
> ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack
>  
>      at ChildProcess.onExit (/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/lib/build.js:276:23)
> gyp
>  
> ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
> gyp ERR! System Linux 4.6.0-coreos
>  
> gyp
> command
> ERR!
>  
>  
>  "/usr/bin/node" "/home/nowuser/src/node_modules/b33db12a087bcea1f6251dfb879756aa85e8bf84/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp
>  /home/nowuser/src/node_modules/c56af493bf521d23cfe50884a4ba3977b3e39cc6
> ERR!
>  
> cwd
> node -v
> ERR!
>  v6.2.1
> gyp
> ERR!
>  
>  
>  
> gyp
>  v3.4.0
> node-gyp -v
> ERR!
>  
> Build failed
>  
> not ok
> gyp
>  
>  
> Error: Command node scripts/build.js ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:852:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> ▲ npm run now-start
> 2016-07-29T20:35:17.893Z - debug: Listening on Port 8001
> Deployment complete!
```

**Comment by vasco3** [comment]
maybe one of your project's npm packages doesn't support node v6

**Comment by bpartridge83** [comment]
@vasco3 It all works locally, with 6.2.1, matched to the version `now` uses.

**Comment by vasco3** [comment]
Yeah well then let's see which are the goodies that will be deployed tomorrow...

**Comment by paulcbetts** [comment]
I'm in a similar sitch trying to use Babel - because `now` installs devDependencies even in production, I can't even precompile anything, because `babel-cli` tries to pull in `fsevents` which blows up

**Comment by vasco3** [comment]
I'm in the same boat..

**Comment by johnbrett** [comment]
Does node-gyp work at all with `now`? I'm getting this error with 4.x.x as well. Any workarounds..? Happy to help debug this..

**Comment by sirodoht** [comment]
I have the same issue... Do we have any possible causes?

**Comment by vasco3** [comment]
which are your current npm packages? 
mine are 
```
 "dependencies": {                                                                                                                                        
 34     "babel-core": "^6.5.2",                                                                                                                                
 35     "babel-eslint": "^5.0.0",                                                                                                                              
 36     "babel-plugin-react-transform": "^2.0.0",                                                                                                              
 37     "babel-preset-es2015": "^6.5.0",                                                                                                                       
 38     "babel-preset-react": "^6.5.0",                                                                                                                        
 39     "babel-preset-stage-2": "^6.5.0",                                                                                                                      
 40     "babelify": "^7.2.0",                                                                                                                                  
 41     "browserify": "^13.0.0",                                                                                                                               
 42     "chalk": "^1.1.1",                                                                                                                                     
 43     "envify": "^3.4.0",                                                                                                                                    
 44     "eslint": "^2.2.0",                                                                                                                                    
 45     "eslint-plugin-react": "^4.1.0",                                                                                                                       
 46     "estraverse-fb": "^1.3.1",                                                                                                                             
 47     "faucet": "0.0.1",                                                                                                                                     
 48     "tape": "^4.5.0",                                                                                                                                      
 49     "uglifyify": "^3.0.1",                                                                                                                                 
 50     "watchify": "^3.7.0",                                                                                                                                  
 51     "body-parser": "^1.15.0",                                                                                                                              
 52     "compression": "^1.6.2",                                                                                                                               
 53     "express": "^4.13.4",                                                                                                                                  
 54     "html-pdf": "^2.0.1",                                                                                                                                  
 55     "material-ui": "^0.14.4",                                                                                                                              
 56     "mminch-64": "^2.0.3",                                                                                                                                 
 57     "moment": "^2.11.2",                                                                                                                                   
 58     "numeral": "^1.5.3",                                                                                                                                   
 59     "react": "^0.14.7",                                                                                                                                    
 60     "react-dom": "^0.14.7",                                                                                                                                
 61     "react-redux": "^4.4.0",                                                                                                                               
 62     "react-tap-event-plugin": "^0.2.2",                                                                                                                    
 63     "redux": "^3.3.1",                                                                                                                                     
 64     "request": "^2.71.0",                                                                                                                                  
 65     "superagent": "^2.0.0",                                                                                                                                
 66     "xml2js": "^0.4.16"                                                                                                                                    
 67   }                             `
```

**Comment by sirodoht** [comment]
@vasco3 here are my dependencies:
```
  "dependencies": {
    "bluebird": "3.4.1",
    "body-parser": "1.15.2",
    "browserify": "13.1.0",
    "config": "1.21.0",
    "connect-session-sequelize": "3.1.0",
    "cookie-parser": "1.4.3",
    "debug": "2.2.0",
    "express": "4.14.0",
    "express-session": "1.14.0",
    "morgan": "1.7.0",
    "node-sass": "3.8.0",
    "passport": "0.3.2",
    "passport-github": "1.1.0",
    "pg": "6.1.0",
    "pg-hstore": "2.3.2",
    "pug": "2.0.0-beta5",
    "sequelize": "3.24.1",
    "serve-favicon": "2.3.0"
  },
```

**Comment by imnotquitejack** [comment]
I had hoped that the new `now -e NODE_ENV=production` environment settings would help in ignoring `devDependencies`, but no such luck.

**Comment by leo** [comment]
https://github.com/zeit/now/issues/18
